# Generated by Django 6.0.5 on 2026-05-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskDescription',
            new_name='Todo',
        ),
    ]
